In [ ]:
def plot_feature_importance(importance, names):
    feature_importance = np.array(importance)
    feature_names = np.array(names)

    data={'feature_names':feature_names,'feature_importance':feature_importance}
    fi_df = pd.DataFrame(data)

    fi_df.sort_values(by=['feature_importance'], ascending=False,inplace=True)
    fi_df.reset_index(drop=True, inplace = True)

    plt.figure(figsize=(10,8))
    sns.barplot(x='feature_importance', y='feature_names', data = fi_df)

    plt.xlabel('FEATURE IMPORTANCE')
    plt.ylabel('FEATURE NAMES')
    plt.grid()

    return fi_df

# 데이터 크롤링

In [3]:
# url의 키 부분은 개인 api키입니다

def traffic_data_crawling(iYear = 2022, pageNo = 1, numOfRows = 10):
    """ 이 함수는 고속도로 공공데이터 포털에서 연도별 이동시간 데이터를 크롤링하기 위한 함수입니다.
    parameters :
        iYear : str : 년도 ex) 2022
        page : int : page number
        page_size : int : one page size
    return :
        type : DataFame of pandas"""
    url = f'http://data.ex.co.kr/openapi/specialAnal/intercityLeadTime?key=**********&type=json&iYear={iYear}&iStUnitCode=101&iEdUnitCode=140&numOfRows={numOfRows}&pageNo={pageNo}'
    response = requests.get(url)
    data = response.json()
    traffic = pd.DataFrame(data)
    traffic_data = pd.DataFrame(traffic['intercityLeadTimeLists'][0], index = [0])

    for i in range (1, traffic.shape[0]):
        traffic_data2 = pd.DataFrame(traffic['intercityLeadTimeLists'][i], index = [i])
        traffic_data = pd.concat([traffic_data, traffic_data2], axis = 0)
    return pd.DataFrame(traffic_data)

stdYear : 기준년도  
sphlDfttNm : 특수일구분명  
sphlDfttCode : 특수일구분코드  
sphlDfttScopTypeNm : 특수일전후특송기간범위구분명  
sphlDfttScopTypeCode : 특수일전후특송기간범위구분코드  
stdHour : 기준시  
stUnitNm : 출발영업소명  
stUnitCode : 출발영업소코드  
edUnitNm : 도착영업소명  
edUnitCode : 도착영업소코드  
dirNm : 방향명  
dirCode : 방향코드  
trtm : 통행시간(분)  
numOfRows : 한 페이지당 출력건수  
pageNo : 출력 페이지번호

In [6]:
traffic_data3_1 = traffic_data_crawling(2021, 10, 30)
traffic_data3_1

,stdHour,iYear,iStUnitCode,iEdUnitCode,stdYear,sphlDfttNm,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,stUnitNm,stUnitCode,edUnitNm,edUnitCode,dirNm,dirCode,trtm,message,code
0,18,None,None,None,2021,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,345.937000000000000000000000,None,None
1,19,None,None,None,2021,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,341.216333333333333333333333,None,None
2,20,None,None,None,2021,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,357.391000000000000000000000,None,None
3,21,None,None,None,2021,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,348.308000000000000000000000,None,None
4,22,None,None,None,2021,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,340.375000000000000000000000,None,None
5,23,None,None,None,2021,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,324.824500000000000000000000,None,None
6,00,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,290.900000000000000000000000,None,None
7,01,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,277.366500000000000000000000,None,None
8,02,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,264.121666666666666666666666,None,None
9,03,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,268.266333333333333333333333,None,None
10,04,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,266.560666666666666666666666,None,None
11,05,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,307.149666666666666666666666,None,None
12,06,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,293.872000000000000000000000,None,None
13,07,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,289.944000000000000000000000,None,None
14,08,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,293.350000000000000000000000,None,None
15,09,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,300.841500000000000000000000,None,None
16,10,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,309.433000000000000000000000,None,None
17,11,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,323.833000000000000000000000,None,None
18,12,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,332.249500000000000000000000,None,None
19,13,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,343.599500000000000000000000,None,None
20,14,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,346.891000000000000000000000,None,None
21,15,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,374.521666666666666666666666,None,None
22,16,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,341.966500000000000000000000,None,None
23,17,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,341.841500000000000000000000,None,None
24,18,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,344.958000000000000000000000,None,None
25,19,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,335.591500000000000000000000,None,None
26,20,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,368.250000000000000000000000,None,None
27,21,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,345.466000000000000000000000,None,None
28,22,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,381.316500000000000000000000,None,None
29,23,None,None,None,2021,추석,3,D-2,2,서울,101,부산,140,귀성방향,1,312.300000000000000000000000,None,None

In [4]:
def traffic_data_choo_crawling(iYear = 2020, pageNostart = 1, pageNoend = 2):
    """ 이 함수는 추석데이터를 뽑아내기 위한 함수입니다.
    parameters :
        iYear : str : 년도 ex) 2022
        pageNostart : int : page start number
        pageNoend : int : page end number
    return :
        type : DataFame of pandas"""
    traffic_data = traffic_data_crawling(iYear, pageNostart, 10)
    
    for i in range (pageNostart + 1, pageNoend):
        traffic_data1 = traffic_data_crawling(iYear, i, 10)
        traffic_data = pd.concat([traffic_data, traffic_data1], axis = 0)
    return pd.DataFrame(traffic_data)

In [9]:
pd.set_option('display.max_row', 10)
dfdf = traffic_data_choo_crawling(2017, 10, 5) # 페이지 넘버를 조절해가며 2017~2021년까지의 추석전후 이틀까지의 데이터를 수집 (단위 : 시간)
# ex) 추석이 10/1이면 9/29~10/3까지의 이동시간 데이터를 수집

In [10]:
drop_col = ['iYear', 'iStUnitCode', 'iEdUnitCode', 'sphlDfttNm', 'stUnitNm', 'edUnitNm', 'stUnitCode', 'edUnitCode', 'dirNm', 'dirCode', 'message', 'code', 'sphlDfttCode']
dfdf1 = dfdf.drop(drop_col, axis = 1)
dfdf1
# dfdf1.to_csv('2017traffic_data') <-- 이후 이 데이터를 각 연도별로 저장

,stdHour,stdYear,sphlDfttScopTypeNm,sphlDfttScopTypeCode,trtm
0,18,2017,D,4,460.300000000000000000000000
1,19,2017,D,4,500.483000000000000000000000
2,20,2017,D,4,527.483000000000000000000000
3,21,2017,D,4,515.916000000000000000000000
4,22,2017,D,4,538.650000000000000000000000
5,23,2017,D,4,529.549500000000000000000000
6,00,2017,D+1,5,360.060666666666666666666666
7,01,2017,D+1,5,315.425000000000000000000000
8,02,2017,D+1,5,311.708000000000000000000000
9,03,2017,D+1,5,307.408000000000000000000000

# 데이터 전처리

# 결측치 확인
- 첨부된 데이터는 이미 결측치가 처리된 데이터이기 때문에 결측치가 나오지 않음

In [ ]:
# data2017traffic = pd.read_csv('2017traffic_data.csv', index_col = [0]) <-- 이동시간 데이터 불러오기
display(data2017traffic[data2017traffic['trtm'].isnull()]) # 결측치 없음
display(data2018traffic[data2018traffic['trtm'].isnull()]) # 추석 하루 뒤 23시, 추석이 지난 후 이므로 크게 중요치 않음, 전후관계를 토대로 적절한 값을 대입
                                                           # interpolate 사용
display(data2019traffic[data2019traffic['trtm'].isnull()]) # 추석 당일, 하루뒤 전부 결측치, 이틀뒤 3개까지, 가장 심각함, 추석 전후 교통량을 토대로 결측치를 추측, 
                                                           # 결측치가 너무 많기 때문에 크게 주의깊게 보지는 않음 그냥 참고정도
                                                           # 2017, 2018의 추석 교통량의 추이가 그래프 상으로 유사하므로 두 데이터의 평균값을 대입
                                                           # 그 후 남은 추석 이틀뒤 값은 interpolate를 사용
display(data2020traffic[data2020traffic['trtm'].isnull()]) # 추석 하루 뒤 23시, 추석 이틀 뒤 0시, 추석이 지난 후 이므로 크게 중요치 않음, 전후관계를 토대로 적절한 값을 대입
                                                           # interpolate 사용
display(data2021traffic[data2021traffic['trtm'].isnull()]) # 추석 이틀 뒤 1~5시, 추석 이틀 뒤 23시, 추석이 지난 후 이므로 크게 중요치 않음, 전후관계를 토대로 적절한 값을 대입
                                                           # KNN Imputer 사용, n_neighbors = 3

### 2017, 2018년도의 데이터 평균값으로 2019 결측치 대입

In [ ]:
a = list((data2018traffic.loc[(data2018traffic['sphlDfttScopTypeNm']== 'D') | (data2018traffic['sphlDfttScopTypeNm']== 'D+1')]['trtm'] + data2017traffic.loc[(data2017traffic['sphlDfttScopTypeNm']== 'D') | (data2017traffic['sphlDfttScopTypeNm']== 'D+1')]['trtm'])/2)

data2019traffic.loc[(data2018traffic['sphlDfttScopTypeNm']== 'D') | (data2018traffic['sphlDfttScopTypeNm']== 'D+1'), 'trtm'] = a
data2019traffic

### 2018, 2019, 2020 전부 interpolate 사용

In [ ]:
data2019traffic_nonna = data2019traffic.interpolate(method='linear')
data2019traffic_nonna.isna().sum()
display(data2019traffic_nonna[95:105])
# data2019traffic_nonna.to_csv('2019traffic_data.csv')
data2018traffic_nonna = data2018traffic.interpolate(method='linear')
data2018traffic_nonna.isna().sum()
display(data2018traffic_nonna[95:105])
# data2018traffic_nonna.to_csv('2018traffic_data.csv')
data2020traffic_nonna = data2020traffic.interpolate(method='linear')
data2020traffic_nonna.isna().sum()
display(data2020traffic_nonna[95:105])
# data2020traffic_nonna.to_csv('2020traffic_data.csv')

### 2021 KNN Imputer 사용

In [ ]:
pd.set_option('display.max_row', 500)
data2021traffic_KNN = data2021traffic.copy()

imputer = KNNImputer(n_neighbors=3)

data_filled = imputer.fit_transform(data2021traffic_KNN['trtm'].values.reshape(-1, 1))
data2021traffic_KNN['trtm'] = pd.DataFrame(data_filled)
data2021traffic_KNN.loc[95:108]
# data2021traffic_KNN.to_csv('2021traffic_data.csv')

# 추가 데이터 수집
- 고속도로 공공데이터 포털 : http://data.ex.co.kr/portal/fdwn/view?type=TCS&num=34&requestfrom=dataset   
에서 TCS 영업소별 교통량 (추석때의 서울톨게이트와 부산톨게이트 교통량) 수집

- 이동시간 데이터와 합치기 위해 2017~2021년까지의 추석전후 이틀까지의 데이터를 수집 (단위 : 시간)

- 파일명은 날짜만 삽입 ex) 20210923.csv

### 수집한 영업소별 교통량 데이터와 이동시간 데이터를 시간대에 맞춰 가로방향으로 concat

In [ ]:
a = pd.read_csv('20210923.csv', index_col = [0])
data20171002 = a.reset_index(drop = True)
data2017traffic = pd.read_csv('2020traffic_data.csv', index_col = [0])
# display(data20171002, data2017traffic)
for i in range(0, 24):
    a = int(round(data2017traffic['trtm'].loc[(data2017traffic['stdHour'] == i) & (data2017traffic['sphlDfttScopTypeCode'] == 6)]))
    b = [a, a, a, a, a, a, a, a]
    data20171002.loc[data20171002['집계시'] == i, '운행시간'] = b
# data20171002.to_csv('C:\\Users\\lak50\\Desktop\\aivle\\추석 교통 소요시간 예측 이벤트\\finaldata\\20210923final.csv')

### concat한 데이터를 전부 불러와서 일별 데이터 5개를 세로방향으로 concat

In [ ]:
all_2021 = pd.concat([final20210919, final20210920, final20210921, final20210922, final20210923], axis = 0)
all_2021['운행시간'].dropna(axis = 0, inplace = True)
del all_2021['Column1']
all_2021
# all_2021.to_csv('all_2021.csv')

### 1시간 단위의 시계열 date를 삽입

In [ ]:
all_2021
all_2017_copy = all_2021.copy()
all_2017_copy1 = all_2017_copy.reset_index(drop = True)

for i in range(all_2017_copy1['집계일자'].shape[0]):
    result1 = str(all_2017_copy1['집계일자'][i])[:4]
    result2 = result1 + '-'
    result3 = result2 + str(all_2017_copy1['집계일자'][i])[4:6]
    result4 = result3 + '-'
    result5 = result4 + str(all_2017_copy1['집계일자'][i])[-2:]
    all_2017_copy1.loc[i, '집계일자'] = result5
a = []
for n in range(all_2017_copy1['집계시'].shape[0]):
    
    result1 = int(all_2017_copy1['집계시'][n])
    if result1 < 10:
        result2 = ' 0' + str(result1) + ':00:00'
    else:
        result2 = ' ' + str(result1) + ':00:00'
    alll = all_2017_copy1.loc[n, '집계일자'] + result2
    all_2017_copy1.iloc[n, 0] = alll

all_2017_copy1['집계일자'] = pd.to_datetime(all_2017_copy1['집계일자'])
display(all_2017_copy1, all_2017_copy1.info())
# all_2017_copy1.to_csv('all_2021_date.csv')

### 컬럼명 변경 후 date를 datetime으로 변경

In [ ]:
all_2017 = pd.read_csv('all_2017_date.csv', index_col = [0])
all_2018 = pd.read_csv('all_2018_date.csv', index_col = [0])
all_2019 = pd.read_csv('all_2019_date.csv', index_col = [0])
all_2020 = pd.read_csv('all_2020_date.csv', index_col = [0])
all_2021 = pd.read_csv('all_2021_date.csv', index_col = [0])

all_list = [all_2017, all_2018, all_2019, all_2020, all_2021]

for i in all_list:
    i.drop(['고속도로운영기관구분코드', '영업형태구분코드'], axis = 1, inplace = True)
    i.rename(columns = {"집계시" : "hour", '집계일자' : 'date', '영업소코드' : 'office_code', '입출구구분코드' : 'in_out_code','TCS하이패스구분코드' : 'tcs_highpass_code' , '1종교통량' : 'traffic_class1', '총교통량' : 'traffic_all', '운행시간' : 'driving_time'}, inplace = True)
    i.insert(5,'traffic_over_class2', i['2종교통량']+i['3종교통량']+i['4종교통량']+i['5종교통량']+i['6종교통량'])
    i.drop(['2종교통량', '3종교통량', '4종교통량', '5종교통량','6종교통량', 'traffic_all'], axis = 1, inplace = True)
for n in all_list:
    n.insert(1, 'day', 0)
    for i in range(n['date'].shape[0]):
        n['date'] = pd.to_datetime(n['date'])
        result1 = str(n['date'][i])[-11:-9]
        n.loc[i, 'day'] = result1
for i in range(5):
    all_list[i] = all_list[i].astype({'driving_time':'int'})
    display(all_list[i].info())
    display(all_list[i])
all_2021 = all_2021.astype({'driving_time':'int'})
all_2021.drop('Column1', axis = 1, inplace = True)
display(all_2021)
# all_2021.to_csv('data_2018.csv')

### 최종 데이터셋

In [ ]:
pd.set_option('display.max_row', 80)
df_2017 = pd.read_csv('data_2017.csv', index_col = [0])
df_2018 = pd.read_csv('data_2018.csv', index_col = [0])
df_2019 = pd.read_csv('data_2019.csv', index_col = [0])
df_2020 = pd.read_csv('data_2020.csv', index_col = [0])
df_2021 = pd.read_csv('data_2021.csv')
df_list = [df_2017, df_2018, df_2019, df_2020, df_2021]
df_2021.drop('Column1', axis = 1, inplace = True)
df_2017['driving_time'] = df_2017['driving_time'].astype('int')
df_2018['driving_time'] = df_2018['driving_time'].astype('int')
for i in df_list:
    i['date'] = pd.to_datetime(i['date'])
    # display(i.info())
    # display(i[10:30])
    # display(i.isna().sum())
df_2017_0 = df_2017.loc[(df_2017['office_code'] == 101)]
df_2018_0 = df_2018.loc[(df_2018['office_code'] == 101)]
df_2019_0 = df_2019.loc[(df_2019['office_code'] == 101)]
df_2020_0 = df_2020.loc[(df_2020['office_code'] == 101)]
df_2021_0 = df_2021.loc[(df_2021['office_code'] == 101)]
df_2017_1 = df_2017.loc[(df_2017['office_code'] == 140)]
df_2018_1 = df_2018.loc[(df_2018['office_code'] == 140)]
df_2019_1 = df_2019.loc[(df_2019['office_code'] == 140)]
df_2020_1 = df_2020.loc[(df_2020['office_code'] == 140)]
df_2021_1 = df_2021.loc[(df_2021['office_code'] == 140)]
    

dumm_cols = ['tcs_highpass_code','office_code','day']
df_2017 = pd.get_dummies(df_2017, columns = dumm_cols, drop_first = False)
dumm_cols = ['tcs_highpass_code','office_code','day']
df_2018 = pd.get_dummies(df_2018, columns = dumm_cols, drop_first = False)
dumm_cols = ['tcs_highpass_code','office_code','day']
df_2019 = pd.get_dummies(df_2019, columns = dumm_cols, drop_first = False)
dumm_cols = ['tcs_highpass_code','office_code','day']
df_2020 = pd.get_dummies(df_2020, columns = dumm_cols, drop_first = False)
dumm_cols = ['tcs_highpass_code','office_code','day']
df_2021 = pd.get_dummies(df_2021, columns = dumm_cols, drop_first = False)

df_2022_0 = df_2020_0.copy()

### 2022년 예측 교통량 데이터

In [ ]:
# 가장 MAE값이 좋았던 2020년도 값을 기준으로 삼고
# 한국교통연구원 설문조사 결과, 교통량 데이터를 바탕으로 비율을 구해 2020년도 데이터에 곱해줌으로서 2022년 교통량 예측 데이터를 생성 --> x_test값으로 대입
# ref : https://biz.chosun.com/policy/policy_sub/2022/09/06/4Q2MEIA4EBCA5DJYII4WBMNU5E/
day_1 = [29, 30, 1, 2, 3]
num2 = [0.576102462137594, 1.0556572650812064, 1.7355014739352899, 1.3206897660148036, 0.84562493739842]
num1 = [0.874151965683776, 1.0086846977461805, 1.2321445597253944, 1.0835826679982143, 0.799219133101926]
for i in range(5):
    df_2022_0.loc[df_2022_0['day'] == i, 'traffic_class1'] = round(df_2022_0.loc[df_2022_0['day'] == i]['traffic_class1']*num1[i]*1.134)
    df_2022_0.loc[df_2022_0['day'] == i, 'traffic_over_class2'] =round(df_2022_0.loc[df_2022_0['day'] == i]['traffic_over_class2']*num2[i]*1.134)

target = 'driving_time'
x_test = df_2022_0.drop([target, 'date'], axis = 1)
x_test.head()

# Machine Learning

In [ ]:
target = 'driving_time'
x = df_2020_0.drop([target, 'date'], axis = 1)
y = df_2020_0.loc[:, target]

In [ ]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = 0.3, shuffle = True)
# 시계열 데이터이기 때문에 shuffle을 False로 두고 SARIMAX 과정을 수행했지만 추석 전날 12:00라는 단기간 데이터 예측이라 그런지 성능이 떨어지는 모델이 나옴
# 따라서 시계열 모델링 수행과정 삽입은 배제함

In [ ]:
# 7개의 모델중 가장 성능이 좋았던 DecisionTree를 이용해 y값을 구함
# 2022년 추석 전날 12:00 이동시간은 316분이 나옴
# 그때의 max_depth = 10
from sklearn.tree import DecisionTreeClassifier, plot_tree

# 평가를 위해.
from sklearn.metrics import *

model_final = DecisionTreeClassifier(max_depth = 10)
model_final.fit(x_train, y_train)
pred_final = model_final.predict(x_test)
df_2022_0['ans'] =  pred_final
df_2022_0['ans'] = df_2022_0['ans']//60*1000 + df_2022_0['ans']%60
display(df_2022_0)
display(df_2022_0.loc[(df_2022_0['day'] == 30) & (df_2022_0['hour'] == 12)])

### Best Model 검증과정

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
x_train_s = scaler.fit_transform(x_train)
x_val_s = scaler.transform(x_val)

In [ ]:
vars, result = forward_stepwise_linear(x_train, y_train)

### 선형회귀 일부 feature

In [ ]:
lr_m1 = LinearRegression()
lr_m1.fit(x_train[vars], y_train)
p1 = lr_m1.predict(x_val[vars])

print('RMSE : ', mean_squared_error(y_val, p1, squared=False))
print('MAE  : ', mean_absolute_error(y_val, p1))
print('MAPE : ', mean_absolute_percentage_error(y_val, p1))

### 선형회귀 전체 feature

In [ ]:
lr_m2 = LinearRegression()
lr_m2.fit(x_train, y_train)
p2 = lr_m2.predict(x_val)

print('RMSE : ', mean_squared_error(y_val, p2, squared=False))
print('MAE  : ', mean_absolute_error(y_val, p2))
print('MAPE : ', mean_absolute_percentage_error(y_val, p2))

### KNN

In [ ]:
params = { 'n_neighbors' : range(3,51,2), 'metric' : ['euclidean', 'manhattan']  }
m = KNeighborsRegressor()

knn_m = GridSearchCV(m, params, cv=5)

knn_m.fit(x_train_s, y_train)
print(knn_m.best_params_)
print(knn_m.best_score_)
p3 = knn_m.predict(x_val_s)
print('RMSE : ', mean_squared_error(y_val, p3, squared=False))
print('MAE  : ', mean_absolute_error(y_val, p3))
print('MAPE : ', mean_absolute_percentage_error(y_val, p3))

### Decision Tree

In [ ]:
params = {'max_depth' : range(2,11)}

m = DecisionTreeRegressor()

dt_m = GridSearchCV(m, params, cv=5, scoring = 'neg_mean_absolute_error')
dt_m.fit(x_train, y_train)
print(dt_m.best_params_)
print(dt_m.best_score_)
p4 = dt_m.predict(x_val)
print('RMSE : ', mean_squared_error(y_val, p4, squared=False))
print('MAE  : ', mean_absolute_error(y_val, p4))
print('MAPE : ', mean_absolute_percentage_error(y_val, p4))

### Randon Forest

In [ ]:
params = {'max_depth' : range(2,21)}
m = RandomForestRegressor()

rf_m = GridSearchCV(m, params, cv=5)
rf_m.fit(x_train, y_train)

print(rf_m.best_params_)
print(rf_m.best_score_)
p5 = rf_m.predict(x_val)
print('RMSE : ', mean_squared_error(y_val, p5, squared=False))
print('MAE  : ', mean_absolute_error(y_val, p5))
print('MAPE : ', mean_absolute_percentage_error(y_val, p5))

### XGB

In [ ]:
params = {'learning_rate' : np.linspace(0.01,0.2, 20), 'n_estimators':range(60,200,20), 'max_depth':[3,4,5,6]}

m = XGBRegressor(objective = 'reg:squarederror')

xgb_m = GridSearchCV(m, params, cv=5)

xgb_m.fit(x_train, y_train)

print(xgb_m.best_params_)
print(xgb_m.best_score_)

print('RMSE : ', mean_squared_error(y_val, p6, squared=False))
print('MAE  : ', mean_absolute_error(y_val, p6))
print('MAPE : ', mean_absolute_percentage_error(y_val, p6))

### SVM

In [ ]:
params = {'C' : np.linspace(0.01, 100, 50), 'gamma':[0.001,0.01,.1,1]}

m = SVR()

svm_m = GridSearchCV(m, params, cv=5)

svm_m.fit(x_train_s, y_train)
print(svm_m.best_params_)
print(svm_m.best_score_)

p7 = svm_m.predict(x_val_s)
print('RMSE : ', mean_squared_error(y_val, p7, squared=False))
print('MAE  : ', mean_absolute_error(y_val, p7))
print('MAPE : ', mean_absolute_percentage_error(y_val, p7))

### 성능비교

In [ ]:
RMSE, MAE, MAPE = [],[],[]
model_desc = ['lr_selected', 'lr_all','knn','dt','rf','xgb','svm']
pred = [p1, p2, p3, p4, p5, p6,p7]

for i, p in enumerate(pred) :
    RMSE.append(mean_squared_error(y_val, p, squared=False))
    MAE.append(mean_absolute_error(y_val, p))
    MAPE.append(mean_absolute_percentage_error(y_val, p))

result = pd.DataFrame({'model_desc':model_desc,'RMSE':RMSE,'MAE':MAE,'MAPE':MAPE})
result.sort_values('MAE')

- 2017  
knn : {'metric': 'manhattan', 'n_neighbors': 13}  
rf : {'max_depth': 2}  
svm : {'C': 59.18775510204081, 'gamma': 0.1}  
<img src="그림1.png">
- 2018  
svm : {'C': 4.091224489795918, 'gamma': 0.1}  
knn : {'metric': 'manhattan', 'n_neighbors': 49}  
xgb : {'learning_rate': 0.03, 'max_depth': 6, 'n_estimators': 100}  
<img src="그림2.png">
- 2019  
dt : {'max_depth': 5}  
xgb : {'learning_rate': 0.02, 'max_depth': 6, 'n_estimators': 100}  
svm : {'C': 14.294285714285714, 'gamma': 0.01}  
<img src="그림3.png">
- 2020  
Knn : {'metric': 'euclidean', 'n_neighbors': 21}  
Svm : {'C': 28.57857142857143, 'gamma': 0.01}  
lr_all : 전체  
<img src="그림4.png">
- 2021  
Xgb : {'learning_rate': 0.02, 'max_depth': 5, 'n_estimators': 180}  
Knn : {'metric': 'euclidean', 'n_neighbors': 27}  
Svm : {'C': 95.91877551020409, 'gamma': 0.01}  
<img src="그림5.png">